variable "vpc_name" {}
variable "cidr_block" {}
variable "env" {}
variable "public_subnet1_cidr" {}
variable "public_subnet2_cidr" {}
variable "public_subnet3_cidr" {}
variable "Public_Subnet-1_name" {}
variable "Public_Subnet-2_name" {}
variable "Public_Subnet-3_name" {}
